language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
#- psql -c 'create database travis_ci_test;' -U postgres
#- psql -c "CREATE USER groupuser WITH PASSWORD 'tutoring!';" -U postgres
#- psql -c "ALTER USER groupuser CREATEDB;" -U postgres
script:
- python manage.py test
branches:
  only:
  - master
services:
  - #postgresql
deploy:
  provider: heroku
  api_key:
    secure: 7cc35d68-f014-43bb-ac31-e00e9d6df8e8
  app: cs4life-quicktutor
  on:
    repo: uva-cs3240-s20/project-101-cs4life
