language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
- python -m pip install Pillow
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c "CREATE USER groupuser WITH PASSWORD 'tutoring!';" -U postgres
- psql -c "ALTER USER groupuser CREATEDB;" -U postgres
script:
- python manage.py test
branches:
  only:
  - master
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: lkoVdjyW2q0bHdGvaKJd/f2WrlcDCI455OUhZBUza08YHJweX2cLJtmeQOmoac2H4Lk+BOkbwXNtvhaxgYN8txbHLOD3Tchu759BkjeZNo3eZhhtTgimoPhVzGYNqQJDtlyqJOWonHTMd+XsC1mZMjlQV5BVPJLqlP61Qd4sjWtr7CRtbnnHFk+TcwKDmgyOmX/m6PTa3eot3Tp2lkUxfXsrdY9Q8/agvr3FXeLsv62GOaIvZLKgQc/pHcsj5iqo1NEnYn44bDrS5DLGvLGZpaxlctGv9hUv35N9z5eAjlFjUziduncfvcJkhcxMfp8/VTcpEK8MsvKhjqqRFX2eIH18T2AsUryts/Ds6uV1il+qWns28uSaca5WzFqsRoAKVij4Uzwl3eNHlYc7fYzUDPel3NhZv3nkVEURpwZgbYhLAuzDR6Cas2BxgacKW7/Psb4R61eGSbhIfoiABanEZDK6CNLhtKn2DIwb2em10QLzPbK1xVwM9ztRLPOi4ZMoJOiCZFX/L2Mp6vw/LVoN9giuODI4SfqAbUCInZr731aBRr8DZFmocH0cdp95pvJYmUKXKu7d8GRl4LNjBULGEY/O+6pPEKmQB1muK4X876XOsATd81ySCEAiXhUdP4zcMjqck9xDHKKcLj5cUYfOsy1EVqfX5dtqzQ4vCRgHeRc=
  app: cs4life-quicktutor
  on:
    repo: uva-cs3240-s20/project-101-cs4life
