language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER groupuser WITH PASSWORD 'tutoring!' CREATEDB SUPERUSER;" -U postgres
script:
- python manage.py test
branches:
  only:
  - master
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: "aJNhEpnw8DV36FZVQCavEHew4OQaEZ4zeKn9J4Ry4R5xuka1EzVncBNTo8xZnIFIPLBKRPt4+gSE3BT4/PKPAOBUGmWTdnWL+KHHgwzZMg0QMkPpAmbLXk5G7wkCzDMaDSxA5OqfEvUw/vFOpCpkQJzjS8+BYwBi3PEAAa
    9YGMj9AInEEjq3HdD9XFlPb6fUy5tWE/X8bM6MirFQDix8zNKr1sTp0zq1DCDsPOya8ZdZephy624+EOXavSYCPLvAmAIb1Mu5IDLh0EaDvIStBqCn+amUzhLAHAvPzfd07CrmhPhVRl4ESy13A7t6nNWa0Kp/Pp7xmJBHknFqC7DAX47
    mIbks/HvaQiFPMsDgdJHgcGcti+Lmkh428vpngJ7M6liJKyQ2r3fRrRqc83oGMCN5thjBavH00F8dmHg6ow5a/fU8jX0f1PR2w4R36NM9LdyodygBOQFnPiP8FMf8sg7hFXNwdcZT09I4gDBZ4CJSxiC7Y8pvJwVUWyLs4W2SeFHICq9K
    ui4m0CPLejlYHGXR5OB1cxDXtarB92HbawvZ8MJPN/+qi8Zc4inPF2CwuQnV+TGP9HTNzJ3fTMRk2rf0b69LPvpRlNG2YMsQd8tGXqMSw8vIhTI1oYTHkuoSzz5o9PzfqUZNAJIPJYWZ3dFesSMafQ9SosA+z6Q3qU8="
  app: cs4life-quicktutor
  on:
    repo: uva-cs3240-s20/project-101-cs4life
