language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: CRdlZevOtRr4fj2WCun08ZB5JlW7K2Rdy47/NV3nzrZNBkcldM+jWod2+q40H8Jo5+pn23wN6iCj1H/F5DtSILNemLPfRZEvulUi5hsfNBQqJt0CW4yAP7XWIk4+NPGABiXDQn9dDCQBxIXsQl9WogmKUbfxaXfzMms5pjFfTkZT26NP07oujKcReJ0gdH68PaFq1oM8TA6Q9chvT3RWC7EyJobRF0MTxfYxtdYKfDFNdG3RQGxxdhE6b9gf6MEICexRzeYJ5CfbVvVw77U7E4LkG5dH1VHQNNDIR5QxQkDfBXAK7vZZsBJLItPgtrdGS7gLM2MN6yDywCIVtu7J7Zk1iMgzaqNA5DS8YRsJxXr7TNPxcq3ji0CMr0jOLL8VkwhdVQ9jkXceiD36bmAgBQV1z6TvRimtZ6kW0uZC3EjTL76U4ITF0zaCwwHxX+4daBigchY5fPBSWGfcCiOqA4ieq7ddS0sO26Wco8o0YvglH24fDn9VD8bKKct69pXV2EClsc81jbFoPmWmouMo8N7nDmDs/zr4o5E3x5HRsq4xSCDBMekR4tigiKxFNBLmlf9z4SJmXHXdygojXOlO5MAJfttx7vEMDXcV0XasG5r1kpBl4qfu+waYUMOGKXB8GrqjS1yv3JYiNtTeRSYVDUaAmpIa3KUJH5FhG4CuLrI=
  app: cs4life-quicktutor
  on:
    repo: uva-cs3240-s20/project-101-cs4life
